/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package checklist;

import java.sql.*;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.apache.derby.jdbc.*;

/**
 *
 * @authors Jessie Collado, Kaelei Lewis, Shiloh Martin-Adam
 */
public final class Start extends javax.swing.JFrame {
    private Connection conn;  //first four lines are for the database
    private ResultSet rs;
    private Statement stmt;
    private final String dbConn = "jdbc:derby:contact;create=true";  //private final String
    ArrayList<String> dropbox = new ArrayList<>();
    String listtracker;


    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
        setDBDirectory();
        createTable();
        getResultSet();
        manageComboBox();
        
    }
    private void setDBDirectory() {
        //Decide on the database location
        String userHomeDir = System.getProperty("user.home", ".");
        String systemDir = userHomeDir + "/checklist";
        //set the db system property
        System.setProperty("derby.system.home", systemDir);
    }
    
        private void createTable() {
        try {
            DriverManager.registerDriver(new EmbeddedDriver());
            conn = DriverManager.getConnection(dbConn);
            String sql = "create table todolist (completestatus boolean default false, taskitem varchar(200), checklistname varchar(50) not null, duedate varchar(20))";
            stmt = conn.createStatement();
            stmt.execute(sql);
        } catch (SQLException e) {
            if (e.getErrorCode() != 30000) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateList = new javax.swing.JButton();
        btnEditList = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create List");

        btnCreateList.setText("Create New List");
        btnCreateList.setToolTipText("");
        btnCreateList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateListActionPerformed(evt);
            }
        });

        btnEditList.setText("Edit Existing List");
        btnEditList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditListActionPerformed(evt);
            }
        });

        jTextField1.setText("New List");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pick a list to add to or edit"}));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete Selected List");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, 0, 236, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditList, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField1))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateList, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditList)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateList)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(554, 126));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditListActionPerformed
        listtracker = jComboBox1.getItemAt(0);
        new ListInsertion(rs, stmt, listtracker).setVisible(true);      
    }//GEN-LAST:event_btnEditListActionPerformed

    private void btnCreateListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateListActionPerformed
        try {
            listtracker = jTextField1.getText();
            //new ListInsertion().setListtracker(listtracker);
            rs = stmt.executeQuery("select * from todolist where checklistname = '" + listtracker + "'");
            jComboBox1.addItem(listtracker);
            jComboBox1.setSelectedItem(listtracker);
            new ListInsertion(rs, stmt).setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnCreateListActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        try {
            listtracker = (String) jComboBox1.getSelectedItem();
            rs = stmt.executeQuery("select * from todolist where checklistname = '" + listtracker + "'");  //this is the SQL query
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            int check = JOptionPane.showConfirmDialog(this, "Delete your list?", "", JOptionPane.YES_NO_OPTION);
            if (check == JOptionPane.YES_OPTION) {
                String listNow = (String) jComboBox1.getSelectedItem();
                rs = stmt.executeQuery("select * from todolist where checklistname = '" + listtracker + "'");  //the SQL query to get the list names
                rs.beforeFirst();  //start at the beginning (we're not inserting, so NOT using movetoinsertrow())
                while (rs.next()) {  //move the cursor forward
                    rs.deleteRow();  //delete the selected list
                }
                jComboBox1.removeItem(listNow);  //Reference:  https://www.w3schools.com/jsref/met_storage_removeitem.asp
                jComboBox1.setSelectedIndex(0);  //Reference:  https://stackoverflow.com/questions/12048864/resetting-the-value-of-a-jcombobox/17871043
                rs.close();  //Reference:  https://stackoverflow.com/questions/4507440/must-jdbc-resultsets-and-statements-be-closed-separately-although-the-connection
                rs = stmt.executeQuery("select * from todolist where checklistname = '" + listtracker + "'");  //query the updated list
                //showResults();  //show the updated list
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateList;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEditList;
    public static javax.swing.JComboBox<String> jComboBox1;
    public static javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables



public void deleteList() {
        //Reference material:  https://www.mkyong.com/swing/java-swing-how-to-make-a-confirmation-dialog/
        try {
            int check = JOptionPane.showConfirmDialog(this, "Delete your list?", "", JOptionPane.YES_NO_OPTION);
            if (check == JOptionPane.YES_OPTION) {
                String listNow = (String) Start.jComboBox1.getSelectedItem();
                rs = stmt.executeQuery("select * from todolist where checklistname = '" + listtracker + "'");  //the SQL query to get the list names
                rs.beforeFirst();  //start at the beginning (we're not inserting, so NOT using movetoinsertrow())
                while (rs.next()) {  //move the cursor forward
                    rs.deleteRow();  //delete the selected list
                }
                Start.jComboBox1.removeItem(listNow);  //Reference:  https://www.w3schools.com/jsref/met_storage_removeitem.asp
                Start.jComboBox1.setSelectedIndex(0);  //Reference:  https://stackoverflow.com/questions/12048864/resetting-the-value-of-a-jcombobox/17871043
                rs.close();  //Reference:  https://stackoverflow.com/questions/4507440/must-jdbc-resultsets-and-statements-be-closed-separately-although-the-connection
                //rs = stmt.executeQuery("select * from todolist where checklistname = '" + listtracker + "'");  //query the updated list
                //showResults();  //show the updated list
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

public void getResultSet() {
        try {
            //stmt = conn.createStatement(java.sql.ResultSet.TYPE_SCROLL_SENSITIVE, java.sql.ResultSet.CONCUR_UPDATABLE);  //able to make changes
            stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);  //able to make changes
            rs = stmt.executeQuery("select * from todolist where checklistname = '" + listtracker + "'");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
}
    
public void manageComboBox() {  //since we're controlling jComboBox1 with a ArrayList, need to set combobox initial state
        try {
            dropbox.add("Pick a list to edit");
            while (rs.next()) {  //while theres any more list names in the list...
                dropbox.add(rs.getString("checklistname"));  //get the next name on the list
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        //Reference for setmodel:  https://stackoverflow.com/questions/3926543/jcomboboxes-using-setmodel-to-access-objects-in-swing
        //new DefaultComboBoxModel(dropbox.toArray());
        //Set unique  = new HashSet(dropbox); //now unique
        //jComboBox1.setModel(new DefaultComboBoxModel(unique.toArray()));
        jComboBox1.setModel(new DefaultComboBoxModel(dropbox.toArray()));
        //to have jComboBox show the list of list names, select jComboBox1, under properties select model, 
        //custom code, then new javax.swing.DefaultComboBoxModel        
    }
}


  
